for f in *_metagenome;
        do SAMPLE=`basename ${f%%_metagenome}`;
        echo "$SAMPLE";
        awk '{print $4}' "$SAMPLE"_diamond.tab > "$SAMPLE"_diamond_matches_list.text;
        echo "extracting genes";
	./faSomeRecords ~/nr.fasta "$SAMPLE"_diamond_matches_list.text "$SAMPLE"_diamond_matches.fasta;
	echo "Biotech_applications";
	grep -i "beta-galactosidase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_beta-galactosidase.txt;
	grep -i "alpha-Amylase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_alpha-Amylase.txt;
	grep -i "Xylanase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Xylanase.txt;
	grep -i "Serine protease"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Serine_protease.txt;
	grep -i "Subtilisin"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Subtilisin.txt;
	grep -i "Serine alkaline protease"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Serine_alkaline_protease.txt;
	grep -i "Acid protease"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Acid_protease.txt;
	grep -i "Subtilisin-like serine protease"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Subtilisin-like_serine_protease.txt;
	grep -i "Protease"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Protease.txt;
	grep -i "Subtilisin-like Serine proteinase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Subtilisin-like_Serine_proteinase.txt;
	grep -i "Aminopeptidase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Aminopeptidase.txt;
	grep -i "Serine peptidase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Serine_peptidase.txt;
	grep -i "Metalloprotease"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Metalloprotease.txt;
	grep -i "Endopeptidase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Endopeptidase.txt;
	grep -i "Lipase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Lipase.txt;
	grep -i "Phytase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Phytase.txt;
	grep -i "Esterase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Esterase.txt;
	grep -i "Epoxide hydrolase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Epoxide_hydrolase.txt;
	grep -i "formylglutathione hydrolase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_formylglutathione_hydrolase.txt;
	grep -i "Polygalacturonase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Polygalacturonase.txt;
	grep -i "Pullulanase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Pullulanase.txt;
	grep -i "Invertase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Invertase.txt;
	grep -i "alpha-glucosidase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_alpha-glucosidase.txt;
	grep -i	 "Cellulase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Cellulase.txt;
	grep -i "Chitobiase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Chitobiase.txt;
	grep -i "Alkaline phosphatase Alkaline"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Alkaline_phosphatase_Alkaline.txt;
	grep -i "Pyrophosphatase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Pyrophosphatase.txt;
	grep -i "Glycerophosphodiesterase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Glycerophosphodiesterase.txt;
	grep -i "Cryonase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Cryonase.txt;
	grep -i "Exonuclease"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Exonuclease.txt;
	grep -i "Uracil-DNA glycosylase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Uracil-DNA_glycosylase.txt;
	grep -i "Phenylalanine hydroxylase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Phenylalanine_hydroxylase.txt;
	grep -i "Alcohol dehydrogenase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Alcohol_dehydrogenase.txt;
	grep -i "Alanine dehydrogenase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Alanine_dehydrogenase.txt;
	grep -i "Leucine dehydrogenase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Leucine_dehydrogenase.txt;
	grep -i "Malate dehydrogenase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Malate_dehydrogenase.txt;
	grep -i "Isocitrate dehydrogenase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Isocitrate_dehydrogenase.txt;
	grep -i "L-threonine dehydrogenase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_L-threonine_dehydrogenase.txt;
	grep -i "Superoxide dismutase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Superoxide_dismutase.txt;
	grep -i "Catalase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Catalase.txt;
	grep -i "Glutathione reductase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Glutathione_reductase.txt;
	grep -i "Glutathione peroxidase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Glutathione_peroxidase.txt;
	grep -i "Thioredoxin reductase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Thioredoxin_reductase.txt;
	grep -i "Glutaredoxin"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Glutaredoxin.txt;
	grep -i "Peroxiredoxin"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Peroxiredoxin.txt;
	grep -i "Dihydroorotate oxidase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Dihydroorotate_oxidase.txt;
	grep -i "Aspartate aminotransferase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Aspartate_aminotransferase.txt;
	grep -i "Glutathione S-transferase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Glutathione_S-transferase.txt;
	grep -i "Hydroxymethyl-transferase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Hydroxymethyl-transferase.txt;
	grep -i "Glutathione synthetase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Glutathione_synthetase.txt;
	grep -i "DNA ligase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_DNA_ligase.txt;
	grep -i "carbonic anhydrase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_carbonic_anhydrase.txt;
	grep -i "Pectate lyase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Pectate_lyase.txt;
	grep -i "Acid decarboxylase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Acid_decarboxylase.txt;
	grep -i "sedoheptulose 7-phosphate isomerase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_sedoheptulose_7-phosphate_isomerase.txt;
	grep -i "Triosephosphate isomerase"  "$SAMPLE"_diamond_matches.fasta > "$SAMPLE"_Triosephosphate_isomerase.txt;
	echo "Counting............";
	grep -c $ "$SAMPLE"_*.txt > "$SAMPLE"_biotech_applications.txt;
done;
